n = str(input('Digite seu nome completo: '))
print(n.upper())
print(n.lower())
print('numero de letras: {}'.format(len(n) - n.count(' ')))
n = n.split()
print('O primeiro nome tem {} letras'.format(len(n[0])))